apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}-data
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{- if .Values.global.volumes.keep }}
    helm.sh/resource-policy: keep
{{- end}}
spec:
  accessModes:
    - {{ .Values.volumes.data.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.data.size }}
  storageClassName: {{ .Values.global.storageClassName }}
